name: Run Tests
on:
  push:
    branches:
      - main
    pull_requests:
      branches:
        - main
jobs:
  tests:
    runs-on: ubuntu-20.04
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Python Virtual Environment
        run: python3 -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./run_test.sh

